#
# Copyright 2021 Hewlett Packard Enterprise Development LP
#
apiVersion: v2
name: cray-precache-images
version: 0.4.0
description: Cache nexus and other images across worker nodes
keywords:
  - precache-images
  - precache
  - images
maintainers:
  - name: bklei
  - name: brantk-hpe
annotations:
  artifacthub.io/changes: |
    - kind: security
      description: Updated images to CSM patched versions
      links:
        - name: Github Issue
          url: https://github.com/Cray-HPE/cray-precache-images/issues/4
        - name: Github PR
          url: https://github.com/Cray-HPE/cray-precache-images/pull/3
  artifacthub.io/images: |
    - name: alpine
      image: alpine:3.14
  artifacthub.io/license: MIT
